In [1]:
import pandas as pd

In [2]:
main_df = pd.read_csv('lomdi1.csv')
main_df.head()

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year
0,2862662347,"Canis latrans Say, 1823",34.699630,-119.241698,9.0,9.0,2020
1,2862658329,"Canis latrans Say, 1823",25.965225,-97.257489,12.0,8.0,2019
2,2862652416,"Canis latrans Say, 1823",43.083987,-89.294833,7.0,9.0,2020
3,2862630361,"Canis latrans Say, 1823",32.710595,-99.730371,13.0,11.0,2019
4,2862630337,"Canis latrans Say, 1823",32.872760,-96.739678,9.0,9.0,2020

In [3]:
main_df.isnull().sum()

gbifID                0
scientificName        0
decimalLatitude     182
decimalLongitude    182
day                 106
month                88
year                  0
dtype: int64

In [4]:
main_df = main_df.dropna()
main_df.isnull().sum()

gbifID              0
scientificName      0
decimalLatitude     0
decimalLongitude    0
day                 0
month               0
year                0
dtype: int64

In [5]:
main_df['day'] = main_df['day'].astype(int).astype(str)
main_df['month'] = main_df['month'].astype(int).astype(str)
main_df['year'] = main_df['year'].astype(int).astype(str)
main_df.head()

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year
0,2862662347,"Canis latrans Say, 1823",34.699630,-119.241698,9,9,2020
1,2862658329,"Canis latrans Say, 1823",25.965225,-97.257489,12,8,2019
2,2862652416,"Canis latrans Say, 1823",43.083987,-89.294833,7,9,2020
3,2862630361,"Canis latrans Say, 1823",32.710595,-99.730371,13,11,2019
4,2862630337,"Canis latrans Say, 1823",32.872760,-96.739678,9,9,2020

In [6]:
temp_df = pd.read_csv('air_temp.csv')
temp_df['measured_on'] = temp_df['measured_on'].astype(str)
temp_df['measured_on'] = temp_df['measured_on'].apply(lambda x: str(int(x[3:5]))+'-'+str(x[6:]))
temp_df = temp_df.set_index('measured_on')
temp_df.head()

,latitude,longitude,maximum temp (deg C),minimum temp (deg C),average temp (deg C)
measured_on,,,,,
1-2003,32.1696,-110.4378,32.1,-0.7,15.5
2-2003,32.1696,-110.4378,32.4,-2.4,13.7
3-2003,32.1696,-110.4378,33.3,1.9,16.2
5-2003,32.1696,-110.4378,43.8,5.5,26.3
6-2003,32.1696,-110.4378,45.4,14.5,30.3

In [7]:
soil_temp_df = pd.read_csv('soil_temp.csv')
soil_temp_df['measured_on'] = soil_temp_df['measured_on'].astype(str)
soil_temp_df['measured_on'] = soil_temp_df['measured_on'].apply(lambda x: str(int(x[3:5]))+'-'+str(x[6:]))
soil_temp_df = soil_temp_df.set_index('measured_on')
soil_temp_df.head()

,latitude,longitude,depth level (cm),maximum temp (deg C),minimum temp (deg C),average temp (deg C)
measured_on,,,,,,
1-2003,32.1696,-110.4378,10,20.9,5.4,13.9
2-2003,32.1696,-110.4378,10,22.1,7.7,14.0
3-2003,32.1696,-110.4378,10,27.0,8.0,17.3
5-2003,32.1696,-110.4378,10,40.2,21.6,30.7
6-2003,32.1696,-110.4378,10,42.1,29.4,35.5

In [8]:
rain_df = pd.read_csv('precipitation.csv')
rain_df['measured_on'] = rain_df['measured_on'].astype(str)
rain_df['measured_on'] = rain_df['measured_on'].apply(lambda x: str(int(x[3:5]))+'-'+str(x[6:]))
rain_df = rain_df.set_index('measured_on')
rain_df.head()

,latitude,longitude,number of days reported,precipitation monthlies
measured_on,,,,
2-2004,32.169600,-110.437800,29,18.3
2-2005,32.169600,-110.437800,28,17.0
12-2017,36.290455,-93.296115,31,51.1
10-2018,36.290455,-93.296115,31,98.5
11-2018,36.290455,-93.296115,30,78.8

In [28]:
aerosol_df = pd.read_csv('aerosol.csv')
aerosol_df = aerosol_df.dropna()
aerosol_df['measured_on'] = aerosol_df['measured_on'].astype(str)
aerosol_df['measured_on'] = aerosol_df['measured_on'].apply(lambda x: str(int(x[3:5]))+'-'+str(x[6:]))
aerosol_df = aerosol_df.drop_duplicates(subset=['measured_on','latitude', 'longitude'])
aerosol_df = aerosol_df.set_index('measured_on')
aerosol_df.head()

              latitude   longitude  optical thickness  transmission percent
measured_on
7-2020       36.290455  -93.296115           0.098131             90.653044
7-2020       45.816720 -118.490850           0.077270             92.563947
7-2020       36.323437  -93.258022           0.122710             88.452013
6-2020       36.323437  -93.258022           0.266350             76.617064
6-2020       36.290455  -93.296115           0.212363             80.867107

In [29]:
aerosol_df.shape

(931, 4)

In [9]:
from math import cos, asin, sqrt

def distance(lat1, lon1, lat2, lon2):
    p = 0.017453292519943295
    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p)*cos(lat2*p) * (1-cos((lon2-lon1)*p)) / 2
    return 12742 * asin(sqrt(a))

def closest(data, v):
    return min(data, key=lambda p: distance(v['decimalLatitude'],v['decimalLongitude'],p['latitude'],p['longitude']))

In [16]:
main_df.tail()

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year
14616,476839066,"Canis latrans Say, 1823",41.617264,-70.475302,27,11,2001
14617,476836969,"Canis latrans Say, 1823",41.700111,-70.032794,23,5,2002
14618,476813864,"Canis latrans Say, 1823",41.519671,-71.372254,1,1,2005
14619,476809540,"Canis latrans Say, 1823",41.700110,-70.299466,8,12,2000
14620,202062058,"Canis latrans Say, 1823",35.230056,-97.297253,2,4,2005

In [13]:
main_df = main_df.reset_index(drop=True)

In [34]:
for i in range (main_df.shape[0]):
    time = main_df.iloc[i][5] + '-' + main_df.iloc[i][6]
    v = main_df.iloc[i][['decimalLatitude','decimalLongitude']].to_dict()
    try:
        time_rain = rain_df.loc[time]
        rain_arr = time_rain[['latitude','longitude']].to_dict('records')
        closest_rain_point = closest(rain_arr, v)
        rain = time_rain[time_rain['latitude']==closest_rain_point['latitude']]['precipitation monthlies'][0]
        main_df.at[i, 'rain'] = rain
    except:
        pass
#         print('rain',time)
    try:
        time_temp = temp_df.loc[time]
        temp_arr = time_temp[['latitude','longitude']].to_dict('records')
        closest_temp_point = closest(temp_arr, v)
        temp = time_temp[time_temp['latitude']==closest_temp_point['latitude']]['average temp (deg C)'][0]
        main_df.at[i, 'temp'] = temp
    except:
#         print('temp',time)
        pass
    try:
        time_soil_temp = soil_temp_df.loc[time]
        soil_temp_arr = time_soil_temp[['latitude','longitude']].to_dict('records')
        closest_soil_temp_point = closest(soil_temp_arr, v)
        soil_temp = time_soil_temp[time_soil_temp['latitude']==closest_soil_temp_point['latitude']]['average temp (deg C)'][0]
        main_df.at[i, 'soil_temp'] = soil_temp
    except:
#         print('soil_temp',time)
        pass
    try:
        time_aerosol = aerosol_df.loc[time]
        aerosol_arr = time_aerosol[['latitude','longitude']].to_dict('records')
        closest_aerosol_point = closest(aerosol_arr, v)
        optical_thickness = time_aerosol[time_aerosol['latitude']==closest_aerosol_point['latitude']]['optical thickness'][0]
        transmission_percent = time_aerosol[time_aerosol['latitude']==closest_aerosol_point['latitude']]['transmission percent'][0]
        main_df.at[i, 'optical_thickness'] = optical_thickness
        main_df.at[i, 'transmission_percent'] = transmission_percent
    except:
        print('aerosol',time,i)
#         pass
main_df.head(15)

aerosol 9-2020 0
aerosol 9-2020 2
aerosol 9-2020 4
aerosol 9-2020 7
aerosol 8-2020 8
aerosol 8-2020 9
aerosol 9-2020 10
aerosol 9-2020 11
aerosol 9-2020 12
aerosol 9-2020 14
aerosol 9-2020 15
aerosol 8-2020 16
aerosol 9-2020 17
aerosol 9-2020 18
aerosol 9-2020 19
aerosol 9-2020 20
aerosol 9-2020 21
aerosol 9-2020 22
aerosol 7-2012 23
aerosol 9-2020 26
aerosol 9-2020 27
aerosol 9-2020 28
aerosol 9-2020 30
aerosol 9-2020 31
aerosol 9-2020 33
aerosol 9-2020 34
aerosol 8-2020 35
aerosol 9-2020 37
aerosol 9-2020 38
aerosol 9-2020 39
aerosol 9-2020 40
aerosol 9-2020 41
aerosol 9-2020 42
aerosol 8-2020 43
aerosol 9-2020 44
aerosol 9-2020 45
aerosol 9-2020 46
aerosol 9-2020 47
aerosol 9-2020 48
aerosol 9-2020 49
aerosol 9-2020 50
aerosol 9-2020 51
aerosol 9-2020 52
aerosol 9-2020 53
aerosol 9-2020 55
aerosol 9-2020 56
aerosol 9-2020 57
aerosol 9-2020 60
aerosol 9-2020 62
aerosol 9-2020 63
aerosol 8-2009 64
aerosol 9-2020 65
aerosol 9-2020 66
aerosol 8-2020 67
aerosol 9-2020 68
aerosol 8-2009 69
aerosol 9-2020 71
aerosol 8-2020 72
aerosol 9-2020 73
aerosol 9-2020 74
aerosol 9-2020 75
aerosol 9-2020 76
aerosol 9-2020 77
aerosol 9-2020 79
aerosol 8-2020 80
aerosol 9-2020 81
aerosol 9-2020 82
aerosol 8-2020 83
aerosol 9-2020 85
aerosol 9-2020 86
aerosol 8-2020 87
aerosol 9-2020 88
aerosol 8-2020 89
aerosol 8-2020 90
aerosol 8-2020 91
aerosol 8-2020 92
aerosol 8-2020 94
aerosol 12-2011 95
aerosol 8-2020 96
aerosol 8-2020 97
aerosol 8-2020 98
aerosol 8-2020 99
aerosol 8-2020 100
aerosol 8-2020 101
aerosol 8-2020 102
aerosol 8-2020 103
aerosol 8-2020 104
aerosol 8-2020 105
aerosol 8-2020 108
aerosol 9-2020 109
aerosol 8-2020 110
aerosol 8-2020 111
aerosol 8-2020 112
aerosol 1-2012 113
aerosol 8-2020 114
aerosol 9-2020 115
aerosol 8-2020 116
aerosol 8-2020 117
aerosol 8-2020 121
aerosol 8-2020 122
aerosol 8-2020 123
aerosol 8-2020 124
aerosol 8-2020 125
aerosol 8-2020 126
aerosol 8-2020 127
aerosol 8-2020 128
aerosol 8-2020 129
aerosol 9-2020 130
aerosol 8-2020 131
aerosol 8-2020 132
aerosol 8-2009 133
aerosol 8-2020 134
aerosol 8-2020 135
aerosol 8-2020 136
aerosol 8-2020 137
aerosol 8-2020 138
aerosol 8-2020 140
aerosol 8-2020 141
aerosol 8-2020 142
aerosol 8-2020 143
aerosol 8-2020 144
aerosol 8-2020 146
aerosol 8-2020 147
aerosol 8-2020 148
aerosol 8-2020 151
aerosol 8-2020 153
aerosol 8-2020 154
aerosol 8-2020 164
aerosol 8-2020 166
aerosol 8-2020 167
aerosol 8-2020 170
aerosol 8-2020 171
aerosol 8-2020 172
aerosol 8-2020 173
aerosol 8-2020 174
aerosol 8-2020 175
aerosol 8-2020 176
aerosol 8-2020 177
aerosol 8-2020 178
aerosol 8-2020 181
aerosol 8-2020 185
aerosol 8-2020 186
aerosol 8-2020 188
aerosol 8-2020 189
aerosol 8-2020 190
aerosol 8-2020 191
aerosol 8-2020 193
aerosol 8-2020 195
aerosol 8-2020 198
aerosol 8-2020 200
aerosol 8-2020 201
aerosol 8-2020 202
aerosol 8-2020 203
aerosol 8-2020 204
aerosol 8-2020 205
aerosol 8-2020 206
aerosol 8-2020 208
aerosol 8-2020 209
aerosol 8-2020 211
aerosol 8-2020 212
aerosol 8-2020 214
aerosol 8-2020 215
aerosol 8-2020 217
aerosol 8-2020 218
aerosol 8-2020 219
aerosol 8-2020 220
aerosol 8-2020 226
aerosol 8-2020 227
aerosol 8-2020 228
aerosol 8-2020 230
aerosol 8-2020 231
aerosol 8-2020 234
aerosol 8-2020 236
aerosol 8-2020 237
aerosol 8-2020 238
aerosol 8-2020 239
aerosol 8-2020 241
aerosol 8-2020 243
aerosol 8-2020 244
aerosol 8-2020 245
aerosol 8-2020 246
aerosol 8-2020 247
aerosol 8-2020 250
aerosol 8-2020 251
aerosol 8-2020 253
aerosol 8-2020 255
aerosol 8-2020 257
aerosol 8-2020 259
aerosol 8-2020 261
aerosol 8-2020 262
aerosol 8-2020 265
aerosol 8-2020 266
aerosol 8-2020 267
aerosol 8-2020 269
aerosol 8-2020 270
aerosol 8-2020 271
aerosol 8-2020 272
aerosol 8-2020 273
aerosol 6-2008 274
aerosol 8-2020 275
aerosol 8-2020 276
aerosol 8-2020 278
aerosol 8-2020 279
aerosol 8-2020 280
aerosol 8-2020 281
aerosol 8-2020 283
aerosol 5-2014 286
aerosol 8-2020 288
aerosol 8-2020 289
aerosol 8-2020 290
aerosol 7-2017 292
aerosol 8-2020 293
aerosol 8-2020 294
aerosol 8-2020 295
aerosol 8-2020 297
aerosol 8-2020 299
aerosol 8-2020 300
aerosol 8-2020 301
aerosol 8-2020 302
aerosol 8-2020 303
aerosol 8-2020 304
aerosol 8-2020 306
aerosol 8-2020 307
aerosol 8-2020 308
aerosol 8-2020 310
aerosol 8-2020 311
aerosol 8-2020 312
aerosol 8-2020 313
aerosol 8-2020 314
aerosol 8-2020 315
aerosol 8-2020 316
aerosol 8-2020 317
aerosol 8-2020 318
aerosol 8-2020 320
aerosol 8-2020 323
aerosol 8-2020 328
aerosol 9-2012 329
aerosol 8-2020 330
aerosol 8-2020 331
aerosol 8-2020 332
aerosol 8-2020 333
aerosol 8-2020 335
aerosol 8-2020 336
aerosol 8-2020 337
aerosol 6-2017 339
aerosol 8-2020 346
aerosol 8-2020 351
aerosol 8-2020 352
aerosol 9-2009 353
aerosol 8-2020 354
aerosol 8-2020 355
aerosol 8-2020 359
aerosol 8-2020 362
aerosol 8-2020 363
aerosol 8-2020 364
aerosol 8-2020 365
aerosol 8-2020 366
aerosol 8-2020 367
aerosol 8-2020 368
aerosol 8-2020 369
aerosol 8-2020 370
aerosol 8-2020 372
aerosol 8-2020 373
aerosol 8-2020 374
aerosol 8-2020 375
aerosol 8-2020 376
aerosol 8-2020 377
aerosol 8-2020 379
aerosol 8-2020 380
aerosol 8-2020 382
aerosol 8-2020 384
aerosol 8-2020 385
aerosol 8-2020 387
aerosol 8-2020 388
aerosol 8-2020 390
aerosol 8-2020 391
aerosol 8-2020 392
aerosol 8-2020 393
aerosol 8-2020 394
aerosol 8-2020 395
aerosol 8-2020 398
aerosol 8-2020 399
aerosol 8-2020 400
aerosol 8-2020 403
aerosol 8-2020 404
aerosol 8-2020 405
aerosol 8-2020 406
aerosol 8-2020 407
aerosol 8-2020 408
aerosol 8-2020 410
aerosol 8-2020 411
aerosol 8-2020 412
aerosol 8-2020 413
aerosol 8-2020 414
aerosol 8-2020 415
aerosol 8-2020 417
aerosol 8-2020 418
aerosol 8-2020 419
aerosol 8-2020 421
aerosol 8-2020 422
aerosol 8-2020 423
aerosol 8-2020 424
aerosol 8-2020 425
aerosol 7-2016 426
aerosol 8-2020 427
aerosol 8-2020 428
aerosol 8-2020 429
aerosol 8-2020 430
aerosol 8-2020 431
aerosol 8-2020 432
aerosol 8-2020 434
aerosol 8-2020 436
aerosol 8-2020 437
aerosol 8-2020 438
aerosol 8-2020 439
aerosol 8-2020 440
aerosol 8-2020 441
aerosol 8-2020 443
aerosol 8-2020 448
aerosol 8-2020 453
aerosol 8-2020 457
aerosol 8-2020 460
aerosol 8-2020 468
aerosol 6-2017 477
aerosol 7-2016 488
aerosol 12-2011 492
aerosol 5-2014 495
aerosol 8-2005 504
aerosol 6-2017 505
aerosol 8-2009 509
aerosol 12-2012 514
aerosol 8-2008 515
aerosol 3-2013 536
aerosol 8-2012 541
aerosol 8-2008 542
aerosol 7-2009 543
aerosol 4-2012 544
aerosol 12-2011 559
aerosol 8-2020 567
aerosol 8-2020 573
aerosol 8-2020 576
aerosol 2-2000 586
aerosol 8-2020 588
aerosol 8-2020 624
aerosol 8-2020 625
aerosol 7-2016 703
aerosol 7-2016 704
aerosol 2-2003 786
aerosol 6-2017 804
aerosol 6-2003 821
aerosol 8-2012 876
aerosol 11-2009 884
aerosol 5-2014 936
aerosol 5-2014 974
aerosol 2-2014 1018
aerosol 2-2001 1040
aerosol 2-2014 1108
aerosol 7-2017 1117
aerosol 7-2013 1125
aerosol 2-2014 1172
aerosol 6-2013 1202
aerosol 6-2013 1216
aerosol 6-2000 1281
aerosol 7-2008 1324
aerosol 1-2014 1364
aerosol 7-2017 1581
aerosol 1-2012 1670
aerosol 8-2014 1690
aerosol 6-2000 1738
aerosol 5-2014 1864
aerosol 8-2014 1948
aerosol 6-2008 1995
aerosol 12-2009 2063
aerosol 9-2009 2096
aerosol 7-2017 2137
aerosol 8-2013 2211
aerosol 5-2014 2237
aerosol 3-2013 2260
aerosol 8-2013 2290
aerosol 6-2017 2306
aerosol 12-2012 2325
aerosol 6-2011 2375
aerosol 4-2012 2566
aerosol 4-2012 2568
aerosol 3-2014 2614
aerosol 12-2011 2615
aerosol 6-2012 2982
aerosol 1-2014 2988
aerosol 6-2013 3033
aerosol 12-2011 3114
aerosol 12-2010 3261
aerosol 1-2014 3405
aerosol 7-2017 3417
aerosol 6-2017 3466
aerosol 8-2009 3514
aerosol 8-2014 3631
aerosol 6-2017 3636
aerosol 6-2017 3661
aerosol 7-2017 3697
aerosol 1-2012 3705
aerosol 2-2014 3736
aerosol 6-2017 3864
aerosol 7-2011 3868
aerosol 4-2012 3871
aerosol 1-2014 3888
aerosol 1-2014 4095
aerosol 1-2014 4144
aerosol 6-2008 4179
aerosol 6-2012 4200
aerosol 3-2014 4227
aerosol 8-2014 4273
aerosol 8-2013 4285
aerosol 1-2012 4301
aerosol 8-2013 4310
aerosol 8-2014 4311
aerosol 8-2010 4320
aerosol 6-2017 4349
aerosol 9-2012 4350
aerosol 12-2012 4377
aerosol 12-2011 4449
aerosol 7-2009 4466
aerosol 8-2013 4507
aerosol 8-2014 4565
aerosol 8-2009 4699
aerosol 2-2014 4799
aerosol 2-2014 4800
aerosol 6-2012 4808
aerosol 7-2012 4821
aerosol 10-2000 4836
aerosol 12-2012 4877
aerosol 7-2012 4955
aerosol 8-2003 4959

aerosol 7-2012 4998
aerosol 6-2010 5023
aerosol 7-2017 5025
aerosol 7-2017 5029
aerosol 5-2014 5040
aerosol 7-2011 5100
aerosol 7-2017 5132
aerosol 7-2011 5151
aerosol 7-2013 5152
aerosol 5-2014 5156
aerosol 9-2012 5191
aerosol 1-2014 5223
aerosol 7-2017 5227
aerosol 1-2014 5239
aerosol 6-2013 5252
aerosol 6-2012 5256
aerosol 8-2014 5300
aerosol 7-2017 5311
aerosol 12-2011 5392
aerosol 7-2011 5426
aerosol 8-2013 5429
aerosol 12-2010 5447
aerosol 6-2009 5450
aerosol 6-2000 5460
aerosol 9-2010 5509
aerosol 9-2010 5531
aerosol 12-2010 5598
aerosol 6-2008 5644
aerosol 7-2017 5686
aerosol 6-2017 5750
aerosol 5-2003 5773
aerosol 7-2016 5785
aerosol 7-2016 5786
aerosol 2-2014 5807
aerosol 5-2014 5812
aerosol 5-2014 5813
aerosol 4-2014 5815
aerosol 1-2014 5816
aerosol 8-2013 5826
aerosol 4-2014 5926
aerosol 6-2017 5993
aerosol 3-2013 6010
aerosol 7-2017 6144
aerosol 2-2014 6151
aerosol 7-2012 6200
aerosol 6-2017 6220
aerosol 8-2013 6226
aerosol 12-2011 6239
aerosol 7-2008 6331
aerosol 2-2014 6334
aerosol 7-2017 6359
aerosol 7-2017 6381
aerosol 7-2016 6393
aerosol 6-2013 6431
aerosol 8-2013 6469
aerosol 8-2012 6521
aerosol 2-2014 6576
aerosol 3-2013 6792
aerosol 6-2012 6797
aerosol 7-2013 6800
aerosol 5-2014 6803
aerosol 7-2013 6804
aerosol 5-2014 6805
aerosol 1-2010 6851
aerosol 1-2010 6856
aerosol 3-2014 6914
aerosol 12-2011 6955
aerosol 8-2013 7114
aerosol 8-2013 7115
aerosol 1-2014 7198
aerosol 7-2017 7220
aerosol 6-2017 7238
aerosol 5-2014 7255
aerosol 5-2014 7256
aerosol 5-2014 7257
aerosol 7-2012 7267
aerosol 5-2014 7279
aerosol 7-2009 7288
aerosol 6-2017 7344
aerosol 7-2012 7346
aerosol 7-2017 7352
aerosol 7-2017 7353
aerosol 4-2012 7453
aerosol 7-2017 7464
aerosol 7-2011 7490
aerosol 9-2010 7502
aerosol 7-2007 7580
aerosol 8-2008 7679
aerosol 7-2017 7737
aerosol 1-2011 7750
aerosol 1-2011 7758
aerosol 8-2014 7807
aerosol 1-2003 7809
aerosol 7-2011 7818
aerosol 3-2013 7875
aerosol 3-2013 7876
aerosol 1-2009 7877
aerosol 6-2017 7913
aerosol 1-2003 7948
aerosol 5-2014 7963
aerosol 6-2017 8027
aerosol 7-2011 8035
aerosol 1-2012 8083
aerosol 12-2011 8098
aerosol 2-2014 8176
aerosol 5-2014 8217
aerosol 1-2014 8237
aerosol 10-2010 8245
aerosol 12-2011 8277
aerosol 11-2009 8293
aerosol 4-2014 8331
aerosol 6-2017 8366
aerosol 9-2012 8397
aerosol 1-2012 8406
aerosol 2-2014 8407
aerosol 5-2014 8408
aerosol 4-2014 8447
aerosol 2-2014 8448
aerosol 6-2017 8457
aerosol 11-2009 8463
aerosol 4-2014 8468
aerosol 12-2008 8475
aerosol 3-2009 8476
aerosol 7-2017 8490
aerosol 1-2011 8560
aerosol 7-2008 8583
aerosol 7-2008 8587
aerosol 8-2009 8589
aerosol 3-2014 8603
aerosol 12-2012 8604
aerosol 5-2014 8608
aerosol 6-2010 8616
aerosol 6-2010 8617
aerosol 6-2010 8619
aerosol 6-2010 8620
aerosol 7-2011 8621
aerosol 11-2009 8622
aerosol 7-2011 8624
aerosol 7-2011 8625
aerosol 11-2009 8626
aerosol 6-2017 8681
aerosol 8-2014 8705
aerosol 7-2012 8718
aerosol 12-2012 8731
aerosol 6-2012 8759
aerosol 12-2008 8762
aerosol 12-2008 8768
aerosol 7-2009 8770
aerosol 7-2009 8771
aerosol 7-2009 8772
aerosol 7-2009 8773
aerosol 7-2009 8774
aerosol 7-2009 8775
aerosol 7-2009 8776
aerosol 7-2009 8777
aerosol 7-2009 8778
aerosol 7-2009 8779
aerosol 9-2009 8780
aerosol 7-2009 8781
aerosol 4-2014 8783
aerosol 7-2009 8786
aerosol 6-2009 8787
aerosol 6-2009 8788
aerosol 7-2009 8789
aerosol 7-2009 8790
aerosol 7-2009 8791
aerosol 7-2009 8792
aerosol 6-2009 8793
aerosol 7-2009 8794
aerosol 6-2009 8795
aerosol 7-2009 8796
aerosol 6-2009 8797
aerosol 6-2009 8798
aerosol 7-2009 8799
aerosol 6-2009 8800
aerosol 7-2008 8803
aerosol 1-2014 8805
aerosol 1-2014 8807
aerosol 1-2014 8808
aerosol 4-2014 8809
aerosol 12-2008 8812
aerosol 12-2012 8813
aerosol 1-2012 8814
aerosol 6-2012 8815
aerosol 8-2014 8834
aerosol 7-2017 8837
aerosol 7-2017 8839
aerosol 5-2014 8840
aerosol 6-2017 8841
aerosol 4-2014 8842
aerosol 3-2014 8843
aerosol 3-2014 8844
aerosol 2-2014 8848
aerosol 6-2012 8864
aerosol 6-2009 8884
aerosol 7-2009 8885
aerosol 6-2009 8886
aerosol 7-2009 8887
aerosol 7-2009 8888
aerosol 6-2009 8889
aerosol 7-2009 8890
aerosol 7-2009 8891
aerosol 8-2009 8892
aerosol 7-2009 8893
aerosol 6-2009 8894
aerosol 8-2009 8895
aerosol 8-2009 8896
aerosol 7-2009 8897
aerosol 6-2009 8898
aerosol 8-2009 8900
aerosol 8-2014 8903
aerosol 6-2017 9004
aerosol 7-2013 9049
aerosol 7-2013 9050
aerosol 8-2013 9083
aerosol 6-2017 9101
aerosol 6-2017 9102
aerosol 6-2017 9104
aerosol 8-2014 9150
aerosol 6-2008 9151
aerosol 7-2017 9159
aerosol 7-2017 9160
aerosol 2-2014 9192
aerosol 2-2014 9228
aerosol 6-2017 9342
aerosol 6-2017 9345
aerosol 6-2017 9405
aerosol 8-2012 9423
aerosol 6-2013 9467
aerosol 12-2012 9535
aerosol 7-2017 9547
aerosol 6-2017 9797
aerosol 6-2017 9831
aerosol 12-2009 9840
aerosol 6-2017 9899
aerosol 4-2014 9908
aerosol 7-2012 9959
aerosol 1-2010 9960
aerosol 7-2007 9998
aerosol 12-2012 10003
aerosol 6-2017 10008
aerosol 7-2017 10027
aerosol 7-2017 10086
aerosol 6-2009 10102
aerosol 6-2011 10118
aerosol 9-2012 10200
aerosol 6-2012 10234
aerosol 7-2017 10239
aerosol 6-2013 10252
aerosol 7-2008 10261
aerosol 7-2007 10262
aerosol 7-2008 10263
aerosol 7-2008 10264
aerosol 7-2008 10265
aerosol 6-2008 10266
aerosol 6-2008 10267
aerosol 7-2008 10268
aerosol 6-2008 10269
aerosol 7-2008 10289
aerosol 7-2008 10291
aerosol 7-2008 10292
aerosol 7-2016 10293
aerosol 8-2009 10301
aerosol 8-2009 10302
aerosol 8-2009 10303
aerosol 9-2009 10304
aerosol 9-2009 10305
aerosol 6-2009 10306
aerosol 8-2009 10307
aerosol 8-2009 10308
aerosol 7-2009 10314
aerosol 7-2009 10315
aerosol 6-2012 10339
aerosol 7-2017 10353
aerosol 7-2017 10357
aerosol 6-2017 10358
aerosol 6-2017 10362
aerosol 7-2017 10363
aerosol 9-2009 10366
aerosol 6-2017 10383
aerosol 6-2017 10385
aerosol 7-2017 10419
aerosol 6-2017 10487
aerosol 7-2017 10488
aerosol 6-2017 10489
aerosol 7-2017 10497
aerosol 11-2009 10504
aerosol 8-2009 10509
aerosol 11-2009 10510
aerosol 12-2009 10511
aerosol 7-2008 10515
aerosol 7-2008 10516
aerosol 7-2017 10536
aerosol 7-2017 10542
aerosol 7-2013 10558
aerosol 7-2016 10559
aerosol 8-2011 10560
aerosol 3-2014 10562
aerosol 7-2017 10617
aerosol 6-2017 10618
aerosol 6-2017 10668
aerosol 7-2017 10673
aerosol 4-2014 10709
aerosol 6-2012 10777
aerosol 6-2012 10778
aerosol 6-2012 10779
aerosol 3-2014 10783
aerosol 6-2017 10821
aerosol 6-2017 10830
aerosol 1-2014 10831
aerosol 6-2012 10832
aerosol 6-2011 10833
aerosol 6-2011 10834
aerosol 6-2011 10835
aerosol 6-2011 10836
aerosol 6-2011 10837
aerosol 6-2011 10838
aerosol 6-2011 10839
aerosol 6-2011 10840
aerosol 6-2011 10842
aerosol 5-2014 10852
aerosol 3-2013 10870
aerosol 7-2017 10872
aerosol 7-2017 10879
aerosol 7-2017 10900
aerosol 7-2017 10904
aerosol 7-2017 10905
aerosol 7-2017 10908
aerosol 7-2017 10909
aerosol 7-2017 10910
aerosol 7-2017 10911
aerosol 7-2017 10912
aerosol 7-2017 10913
aerosol 7-2017 10914
aerosol 7-2017 10915
aerosol 7-2017 10924
aerosol 7-2017 10925
aerosol 7-2017 10926
aerosol 7-2017 10927
aerosol 7-2017 10929
aerosol 7-2017 10933
aerosol 7-2017 10934
aerosol 7-2017 10935
aerosol 6-2017 10936
aerosol 7-2017 10937
aerosol 1-2014 10938
aerosol 7-2017 10940
aerosol 7-2017 10941
aerosol 7-2017 10942
aerosol 7-2017 10943
aerosol 7-2017 10945
aerosol 7-2017 10947
aerosol 7-2017 10949
aerosol 7-2017 10950
aerosol 7-2017 10951
aerosol 4-2012 10952
aerosol 8-2012 10953
aerosol 7-2017 10954
aerosol 7-2017 10955
aerosol 7-2017 10956
aerosol 7-2017 10957
aerosol 8-2012 10958
aerosol 7-2017 10963
aerosol 7-2017 10965
aerosol 6-2017 10966
aerosol 9-2012 10969
aerosol 7-2017 10970
aerosol 7-2017 10973
aerosol 7-2017 10974
aerosol 7-2017 10975
aerosol 7-2017 10976
aerosol 7-2016 10977
aerosol 7-2017 10978
aerosol 7-2017 10979
aerosol 7-2017 10980
aerosol 7-2017 10981
aerosol 7-2017 10982
aerosol 6-2017 10983
aerosol 6-2017 10984
aerosol 7-2017 10985
aerosol 7-2017 10986
aerosol 7-2017 10987
aerosol 7-2017 10988
aerosol 7-2017 10989
aerosol 6-2017 10990
aerosol 7-2017 10992
aerosol 6-2017 10993
aerosol 4-2014 10995
aerosol 7-2017 10996
aerosol 7-2017 10997
aerosol 7-2017 10998
aerosol 7-2017 10999
aerosol 6-2017 11000
aerosol 7-2017 11001
aerosol 7-2017 11002
aerosol 6-2017 11003
aerosol 6-2013 11004
aerosol 6-2017 11005
aerosol 6-2017 11006
aerosol 6-2017 11007
aerosol 6-2017 11008
aerosol 6-2017 11010
aerosol 6-2017 11011
aerosol 2-2014 11012
aerosol 6-2017 11013
aerosol 6-2017 11014
aerosol 6-2017 11015
aerosol 6-2017 11016
aerosol 6-2017 11017
aerosol 6-2017 11018
aerosol 6-2017 11019
aerosol 6-2017 11020
aerosol 6-2017 11021

aerosol 6-2017 11022
aerosol 6-2017 11023
aerosol 6-2017 11025
aerosol 6-2017 11026
aerosol 6-2017 11027
aerosol 6-2017 11028
aerosol 6-2017 11029
aerosol 6-2017 11030
aerosol 6-2017 11031
aerosol 6-2017 11032
aerosol 6-2017 11033
aerosol 6-2017 11034
aerosol 7-2016 11035
aerosol 6-2017 11036
aerosol 6-2017 11037
aerosol 6-2017 11038
aerosol 6-2017 11039
aerosol 6-2017 11041
aerosol 6-2017 11042
aerosol 6-2017 11043
aerosol 6-2017 11044
aerosol 6-2017 11045
aerosol 6-2017 11048
aerosol 6-2017 11049
aerosol 6-2017 11051
aerosol 6-2017 11052
aerosol 6-2017 11053
aerosol 6-2017 11054
aerosol 6-2017 11056
aerosol 6-2017 11057
aerosol 6-2017 11058
aerosol 6-2017 11060
aerosol 6-2017 11061
aerosol 6-2017 11062
aerosol 6-2017 11063
aerosol 6-2017 11064
aerosol 6-2017 11067
aerosol 6-2017 11071
aerosol 6-2017 11072
aerosol 6-2017 11073
aerosol 6-2017 11074
aerosol 6-2017 11075
aerosol 6-2017 11076
aerosol 6-2017 11078
aerosol 6-2017 11079
aerosol 6-2017 11082
aerosol 6-2017 11083
aerosol 6-2017 11084
aerosol 6-2010 11086
aerosol 6-2017 11089
aerosol 6-2017 11091
aerosol 6-2017 11095
aerosol 6-2017 11097
aerosol 6-2017 11100
aerosol 6-2017 11101
aerosol 6-2017 11102
aerosol 6-2017 11103
aerosol 6-2017 11104
aerosol 6-2017 11105
aerosol 6-2017 11108
aerosol 8-2013 11166
aerosol 9-2010 11204
aerosol 7-2011 11225
aerosol 7-2016 11262
aerosol 6-2011 11270
aerosol 3-2014 11314
aerosol 7-2016 11327
aerosol 4-2014 11329
aerosol 4-2014 11330
aerosol 2-2014 11390
aerosol 5-2014 11450
aerosol 5-2014 11451
aerosol 3-2014 11452
aerosol 3-2014 11453
aerosol 7-2016 11476
aerosol 7-2016 11494
aerosol 8-2012 11516
aerosol 8-2009 11528
aerosol 12-2010 11538
aerosol 1-2014 11585
aerosol 1-2014 11639
aerosol 12-2011 11737
aerosol 1-2010 11742
aerosol 8-2010 11745
aerosol 7-2016 11762
aerosol 7-2016 11793
aerosol 3-2014 11797
aerosol 7-2016 11940
aerosol 5-2014 12071
aerosol 8-2014 12130
aerosol 8-2014 12138
aerosol 1-2010 12141
aerosol 3-2014 12146
aerosol 1-2014 12152
aerosol 7-2013 12164
aerosol 6-2013 12171
aerosol 3-2013 12234
aerosol 7-2016 12240
aerosol 7-2016 12241
aerosol 7-2016 12242
aerosol 9-2012 12243
aerosol 7-2013 12245
aerosol 7-2000 12333
aerosol 9-2003 12334
aerosol 1-2014 12340
aerosol 12-2012 12359
aerosol 1-2012 12360
aerosol 6-2013 12401
aerosol 2-2014 12411
aerosol 7-2016 12421
aerosol 9-2012 12429
aerosol 7-2016 12445
aerosol 6-2013 12446
aerosol 1-2014 12452
aerosol 8-2013 12456
aerosol 7-2016 12461
aerosol 7-2016 12470
aerosol 7-2016 12476
aerosol 7-2016 12483
aerosol 5-2014 12488
aerosol 7-2016 12491
aerosol 7-2016 12492
aerosol 7-2016 12501
aerosol 7-2016 12502
aerosol 7-2016 12504
aerosol 7-2016 12505
aerosol 7-2012 12509
aerosol 6-2012 12510
aerosol 8-2014 12524
aerosol 7-2016 12525
aerosol 7-2016 12526
aerosol 7-2016 12527
aerosol 7-2016 12528
aerosol 7-2016 12529
aerosol 7-2016 12530
aerosol 7-2016 12531
aerosol 7-2016 12532
aerosol 7-2016 12533
aerosol 7-2016 12534
aerosol 7-2016 12535
aerosol 7-2016 12536
aerosol 1-2014 12538
aerosol 6-2010 12541
aerosol 6-2010 12542
aerosol 7-2016 12544
aerosol 7-2016 12545
aerosol 7-2016 12547
aerosol 7-2016 12548
aerosol 7-2016 12549
aerosol 7-2016 12550
aerosol 7-2016 12551
aerosol 7-2016 12552
aerosol 7-2016 12553
aerosol 7-2016 12554
aerosol 7-2016 12555
aerosol 7-2016 12556
aerosol 7-2016 12557
aerosol 7-2016 12559
aerosol 7-2016 12560
aerosol 7-2016 12561
aerosol 7-2016 12562
aerosol 7-2016 12563
aerosol 7-2016 12564
aerosol 7-2016 12566
aerosol 7-2016 12571
aerosol 7-2016 12572
aerosol 7-2016 12573
aerosol 7-2016 12574
aerosol 7-2016 12575
aerosol 7-2016 12576
aerosol 7-2016 12577
aerosol 7-2016 12578
aerosol 7-2016 12580
aerosol 7-2016 12581
aerosol 7-2016 12582
aerosol 7-2016 12583
aerosol 7-2016 12584
aerosol 7-2016 12585
aerosol 7-2016 12586
aerosol 7-2016 12587
aerosol 7-2016 12588
aerosol 7-2016 12589
aerosol 7-2016 12592
aerosol 5-2014 12593
aerosol 7-2016 12595
aerosol 7-2016 12596
aerosol 7-2016 12597
aerosol 7-2016 12598
aerosol 3-2013 12645
aerosol 6-2013 12664
aerosol 8-2012 12665
aerosol 8-2013 12677
aerosol 3-2014 12691
aerosol 7-2012 12761
aerosol 7-2009 12762
aerosol 8-2012 12782
aerosol 7-2013 12792
aerosol 6-2012 12807
aerosol 8-2012 12808
aerosol 6-2012 12810
aerosol 7-2012 12811
aerosol 1-2011 12832
aerosol 9-2009 12836
aerosol 8-2001 12862
aerosol 8-2014 12877
aerosol 8-2011 12894
aerosol 6-2012 12958
aerosol 8-2013 13011
aerosol 8-2014 13036
aerosol 8-2009 13040
aerosol 7-2013 13072
aerosol 6-2011 13102
aerosol 4-2012 13103
aerosol 4-2012 13104
aerosol 3-2013 13114
aerosol 8-2011 13122
aerosol 12-2011 13172
aerosol 3-2014 13173
aerosol 3-2013 13217
aerosol 12-2012 13230
aerosol 9-2012 13233
aerosol 6-2008 13267
aerosol 9-2000 13273
aerosol 9-2000 13275
aerosol 5-2001 13276
aerosol 9-2000 13277
aerosol 9-2000 13278
aerosol 9-2000 13282
aerosol 6-2013 13288
aerosol 6-2010 13290
aerosol 9-2000 13294
aerosol 9-2000 13295
aerosol 1-2001 13297
aerosol 6-2009 13300
aerosol 6-2003 13301
aerosol 7-2003 13303
aerosol 7-2003 13304
aerosol 8-2003 13305
aerosol 8-2003 13306
aerosol 6-2008 13311
aerosol 8-2012 13319
aerosol 9-2012 13321
aerosol 4-2012 13323
aerosol 4-2012 13324
aerosol 4-2012 13325
aerosol 4-2012 13326
aerosol 7-2008 13327
aerosol 1-2011 13336
aerosol 12-2008 13352
aerosol 7-2008 13353
aerosol 1-2009 13355
aerosol 1-2003 13371
aerosol 1-2003 13375
aerosol 1-2003 13378
aerosol 2-2003 13379
aerosol 8-2003 13380
aerosol 3-2000 13382
aerosol 2-2003 13393
aerosol 10-2000 13398
aerosol 11-2000 13399
aerosol 1-2014 13403
aerosol 6-2012 13404
aerosol 11-2009 13406
aerosol 1-2011 13407
aerosol 2-2009 13408
aerosol 2-2009 13409
aerosol 5-2014 13433
aerosol 5-2014 13434
aerosol 5-2014 13435
aerosol 5-2014 13436
aerosol 3-2014 13437
aerosol 1-2012 13458
aerosol 8-2013 13491
aerosol 7-2013 13492
aerosol 7-2005 13515
aerosol 1-2014 13517
aerosol 8-2013 13523
aerosol 8-2013 13537
aerosol 1-2014 13546
aerosol 2-2003 13559
aerosol 11-2010 13596
aerosol 11-2009 13648
aerosol 1-2014 13649
aerosol 4-2014 13657
aerosol 10-2010 13664
aerosol 1-2012 13695
aerosol 4-2014 13714
aerosol 11-2010 13719
aerosol 12-2011 13722
aerosol 8-2014 13726
aerosol 8-2014 13728
aerosol 9-2012 13734
aerosol 5-2014 13767
aerosol 3-2014 13771
aerosol 8-2014 13776
aerosol 8-2014 13790
aerosol 12-2009 13791
aerosol 8-2014 13792
aerosol 1-2011 13793
aerosol 8-2014 13794
aerosol 8-2014 13795
aerosol 8-2014 13796
aerosol 8-2014 13797
aerosol 8-2014 13800
aerosol 4-2014 13802
aerosol 8-2014 13803
aerosol 8-2014 13804
aerosol 8-2014 13806
aerosol 8-2014 13807
aerosol 1-2014 13813
aerosol 3-2014 13821
aerosol 2-2014 13822
aerosol 4-2012 13823
aerosol 8-2009 13824
aerosol 3-2001 13826
aerosol 9-2009 13829
aerosol 8-2008 13845
aerosol 5-2014 13847
aerosol 5-2014 13848
aerosol 5-2014 13849
aerosol 4-2014 13851
aerosol 5-2014 13852
aerosol 5-2014 13853
aerosol 5-2014 13854
aerosol 6-2011 13855
aerosol 5-2014 13856
aerosol 5-2014 13857
aerosol 1-2014 13858
aerosol 5-2014 13859
aerosol 3-2014 13860
aerosol 3-2014 13861
aerosol 5-2014 13862
aerosol 5-2014 13863
aerosol 5-2014 13864
aerosol 5-2014 13865
aerosol 5-2014 13866
aerosol 4-2014 13867
aerosol 3-2014 13868
aerosol 6-2013 13870
aerosol 6-2012 13872
aerosol 4-2014 13876
aerosol 2-2014 13877
aerosol 4-2014 13879
aerosol 4-2014 13880
aerosol 3-2014 13881
aerosol 4-2014 13882
aerosol 11-2010 13883
aerosol 4-2014 13884
aerosol 3-2014 13885
aerosol 1-2014 13886
aerosol 3-2014 13887
aerosol 3-2014 13888
aerosol 3-2014 13889
aerosol 3-2014 13890
aerosol 3-2014 13891
aerosol 3-2014 13892
aerosol 3-2014 13893
aerosol 3-2014 13894
aerosol 3-2014 13895
aerosol 3-2014 13896
aerosol 3-2014 13897
aerosol 3-2014 13898
aerosol 2-2014 13899
aerosol 2-2014 13900
aerosol 3-2014 13901
aerosol 3-2014 13902
aerosol 3-2014 13903
aerosol 3-2014 13904
aerosol 2-2014 13905
aerosol 3-2014 13906
aerosol 3-2014 13907
aerosol 3-2014 13908
aerosol 3-2014 13909
aerosol 3-2014 13910
aerosol 3-2014 13911
aerosol 3-2014 13912
aerosol 3-2014 13913
aerosol 3-2014 13916
aerosol 2-2014 13917
aerosol 7-2013 13918
aerosol 1-2014 13919
aerosol 1-2014 13920
aerosol 8-2012 13921
aerosol 1-2014 13922
aerosol 3-2013 13929
aerosol 8-2005 13930
aerosol 7-2005 13931
aerosol 1-2003 13932
aerosol 2-2003 13933
aerosol 11-2000 13934
aerosol 1-2003 13936
aerosol 2-2001 13937
aerosol 11-2000 13938
aerosol 1-2009 13939
aerosol 12-2009 13940
aerosol 9-2010 13941
aerosol 11-2010 13942
aerosol 11-2010 13943
aerosol 4-2001 13944

aerosol 8-2008 13945
aerosol 8-2008 13946
aerosol 8-2008 13947
aerosol 8-2008 13948
aerosol 8-2008 13949
aerosol 8-2008 13950
aerosol 8-2008 13951
aerosol 8-2008 13952
aerosol 8-2008 13953
aerosol 8-2008 13954
aerosol 8-2008 13955
aerosol 6-2000 13957
aerosol 4-2000 13958
aerosol 6-2000 13960
aerosol 11-2010 13961
aerosol 11-2010 13962
aerosol 1-2014 13963
aerosol 1-2014 13965
aerosol 12-2011 13981
aerosol 2-2009 13989
aerosol 9-2009 13990
aerosol 8-2012 14009
aerosol 12-2011 14012
aerosol 6-2013 14038
aerosol 4-2000 14040
aerosol 9-2000 14041
aerosol 8-2013 14042
aerosol 8-2013 14043
aerosol 8-2013 14045
aerosol 8-2013 14046
aerosol 8-2013 14047
aerosol 6-2009 14048
aerosol 2-2009 14049
aerosol 8-2013 14050
aerosol 12-2011 14052
aerosol 8-2011 14053
aerosol 6-2013 14054
aerosol 8-2008 14055
aerosol 1-2010 14056
aerosol 3-2009 14057
aerosol 8-2013 14058
aerosol 8-2013 14059
aerosol 8-2013 14060
aerosol 12-2010 14061
aerosol 6-2013 14062
aerosol 7-2013 14063
aerosol 7-2013 14064
aerosol 7-2013 14065
aerosol 12-2012 14067
aerosol 6-2013 14068
aerosol 7-2013 14069
aerosol 7-2013 14070
aerosol 6-2011 14071
aerosol 7-2013 14072
aerosol 7-2013 14073
aerosol 12-2012 14074
aerosol 6-2013 14075
aerosol 6-2013 14076
aerosol 6-2013 14077
aerosol 6-2013 14078
aerosol 6-2013 14079
aerosol 6-2013 14080
aerosol 8-2012 14085
aerosol 8-2012 14086
aerosol 1-2012 14087
aerosol 12-2011 14088
aerosol 6-2013 14090
aerosol 6-2013 14092
aerosol 6-2013 14093
aerosol 3-2013 14094
aerosol 9-2009 14100
aerosol 3-2013 14105
aerosol 4-2012 14106
aerosol 3-2013 14112
aerosol 3-2013 14113
aerosol 3-2013 14114
aerosol 6-2012 14115
aerosol 3-2013 14116
aerosol 3-2013 14117
aerosol 3-2013 14118
aerosol 3-2013 14120
aerosol 3-2013 14121
aerosol 7-2011 14123
aerosol 7-2011 14124
aerosol 12-2011 14125
aerosol 3-2009 14136
aerosol 12-2012 14143
aerosol 12-2012 14144
aerosol 12-2012 14145
aerosol 12-2012 14146
aerosol 12-2012 14147
aerosol 12-2012 14148
aerosol 1-2010 14152
aerosol 7-2012 14155
aerosol 7-2012 14156
aerosol 8-2012 14157
aerosol 12-2011 14158
aerosol 8-2011 14159
aerosol 9-2009 14160
aerosol 9-2012 14161
aerosol 9-2012 14162
aerosol 9-2012 14163
aerosol 8-2012 14164
aerosol 8-2012 14165
aerosol 8-2012 14166
aerosol 8-2012 14167
aerosol 8-2012 14169
aerosol 8-2012 14170
aerosol 8-2008 14171
aerosol 8-2012 14172
aerosol 7-2012 14173
aerosol 6-2012 14174
aerosol 6-2012 14175
aerosol 4-2012 14180
aerosol 6-2003 14182
aerosol 4-2012 14183
aerosol 4-2012 14184
aerosol 6-2003 14185
aerosol 6-2009 14188
aerosol 1-2012 14192
aerosol 2-2009 14193
aerosol 1-2012 14194
aerosol 1-2012 14195
aerosol 12-2011 14196
aerosol 12-2010 14197
aerosol 7-2011 14198
aerosol 6-2011 14205
aerosol 3-2009 14210
aerosol 2-2009 14211
aerosol 3-2014 14214
aerosol 2-2014 14215
aerosol 3-2014 14216
aerosol 2-2014 14218
aerosol 7-2013 14220
aerosol 8-2013 14221
aerosol 2-2014 14223
aerosol 2-2014 14224
aerosol 2-2014 14226
aerosol 2-2014 14227
aerosol 2-2014 14228
aerosol 12-2008 14232
aerosol 2-2014 14233
aerosol 2-2014 14234
aerosol 2-2014 14236
aerosol 1-2014 14237
aerosol 2-2014 14238
aerosol 2-2014 14239
aerosol 2-2014 14240
aerosol 2-2014 14242
aerosol 1-2014 14243
aerosol 2-2014 14244
aerosol 2-2014 14245
aerosol 1-2014 14246
aerosol 1-2014 14247
aerosol 1-2014 14248
aerosol 1-2014 14249
aerosol 1-2014 14250
aerosol 1-2014 14251
aerosol 1-2014 14252
aerosol 1-2014 14253
aerosol 1-2014 14254
aerosol 1-2014 14255
aerosol 1-2014 14256
aerosol 1-2014 14257
aerosol 1-2014 14259
aerosol 6-2013 14261
aerosol 6-2009 14262
aerosol 9-2012 14264
aerosol 12-2012 14266
aerosol 2-2009 14271
aerosol 2-2009 14273
aerosol 2-2009 14277
aerosol 1-2001 14278
aerosol 2-2009 14280
aerosol 1-2001 14283
aerosol 2-2001 14285
aerosol 2-2009 14286
aerosol 2-2001 14287
aerosol 2-2009 14288
aerosol 3-2001 14292
aerosol 3-2001 14293
aerosol 12-2008 14294
aerosol 1-2009 14296
aerosol 1-2009 14297
aerosol 1-2009 14298
aerosol 2-2001 14300
aerosol 1-2001 14301
aerosol 1-2009 14303
aerosol 1-2001 14304
aerosol 12-2000 14306
aerosol 1-2001 14307
aerosol 1-2009 14309
aerosol 1-2001 14311
aerosol 1-2001 14314
aerosol 1-2009 14315
aerosol 1-2001 14317
aerosol 1-2001 14318
aerosol 12-2000 14321
aerosol 11-2009 14322
aerosol 1-2009 14324
aerosol 2-2009 14326
aerosol 3-2001 14327
aerosol 1-2001 14329
aerosol 11-2009 14332
aerosol 3-2001 14334
aerosol 2-2009 14335
aerosol 1-2009 14336
aerosol 1-2001 14339
aerosol 1-2001 14341
aerosol 1-2009 14343
aerosol 2-2009 14344
aerosol 2-2009 14347
aerosol 1-2001 14348
aerosol 1-2009 14349
aerosol 2-2009 14350
aerosol 2-2009 14351
aerosol 1-2001 14352
aerosol 12-2010 14354
aerosol 12-2008 14356
aerosol 1-2001 14357
aerosol 2-2009 14358
aerosol 12-2008 14360
aerosol 12-2000 14361
aerosol 1-2009 14362
aerosol 1-2001 14363
aerosol 2-2009 14364
aerosol 1-2009 14365
aerosol 12-2008 14366
aerosol 1-2009 14368
aerosol 2-2009 14369
aerosol 1-2009 14370
aerosol 12-2008 14371
aerosol 1-2001 14372
aerosol 2-2009 14373
aerosol 2-2009 14374
aerosol 1-2001 14375
aerosol 1-2009 14376
aerosol 1-2009 14377
aerosol 1-2001 14378
aerosol 1-2001 14379
aerosol 1-2001 14380
aerosol 1-2009 14381
aerosol 1-2001 14382
aerosol 1-2001 14384
aerosol 1-2001 14385
aerosol 2-2001 14386
aerosol 1-2001 14387
aerosol 1-2009 14388
aerosol 1-2001 14389
aerosol 1-2001 14390
aerosol 2-2009 14391
aerosol 1-2001 14392
aerosol 1-2001 14393
aerosol 1-2001 14394
aerosol 1-2001 14395
aerosol 2-2009 14396
aerosol 1-2001 14397
aerosol 1-2001 14399
aerosol 1-2001 14400
aerosol 2-2001 14401
aerosol 1-2001 14402
aerosol 1-2001 14403
aerosol 1-2001 14404
aerosol 1-2001 14405
aerosol 2-2001 14406
aerosol 2-2001 14407
aerosol 1-2001 14408
aerosol 2-2009 14410
aerosol 1-2001 14411
aerosol 1-2001 14412
aerosol 12-2000 14413
aerosol 2-2001 14414
aerosol 1-2009 14415
aerosol 1-2001 14416
aerosol 1-2001 14417
aerosol 1-2001 14418
aerosol 1-2001 14419
aerosol 1-2001 14420
aerosol 1-2001 14421
aerosol 2-2001 14422
aerosol 1-2001 14423
aerosol 1-2001 14424
aerosol 1-2001 14425
aerosol 1-2001 14426
aerosol 2-2001 14428
aerosol 1-2001 14429
aerosol 1-2001 14430
aerosol 1-2001 14431
aerosol 1-2001 14433
aerosol 2-2001 14434
aerosol 2-2001 14435
aerosol 2-2001 14436
aerosol 12-2000 14437
aerosol 2-2009 14439
aerosol 1-2001 14440
aerosol 1-2001 14441
aerosol 1-2001 14442
aerosol 1-2001 14443
aerosol 12-2000 14444
aerosol 12-2008 14445
aerosol 1-2001 14446
aerosol 1-2001 14447
aerosol 3-2001 14448
aerosol 1-2001 14449
aerosol 2-2009 14450
aerosol 1-2001 14451
aerosol 1-2001 14452
aerosol 1-2001 14453
aerosol 1-2001 14454
aerosol 12-2000 14455
aerosol 1-2001 14456
aerosol 1-2001 14457
aerosol 1-2001 14459
aerosol 2-2001 14463
aerosol 1-2001 14465
aerosol 1-2001 14468
aerosol 12-2000 14471
aerosol 1-2001 14477
aerosol 9-2003 14525
aerosol 2-2003 14535
aerosol 5-2003 14553
aerosol 2-2003 14558
aerosol 2-2001 14559
aerosol 2-2001 14561
aerosol 2-2001 14562
aerosol 2-2001 14563
aerosol 2-2001 14564
aerosol 2-2001 14565
aerosol 2-2001 14566
aerosol 5-2001 14567
aerosol 2-2001 14568
aerosol 2-2001 14569
aerosol 2-2001 14570
aerosol 2-2001 14572
aerosol 2-2001 14573
aerosol 11-2000 14574
aerosol 2-2001 14575
aerosol 2-2001 14576
aerosol 2-2001 14577
aerosol 2-2001 14578
aerosol 2-2001 14579
aerosol 2-2001 14580
aerosol 2-2001 14581
aerosol 2-2001 14582
aerosol 2-2001 14584
aerosol 2-2001 14585
aerosol 1-2001 14586
aerosol 1-2001 14587
aerosol 1-2001 14588
aerosol 1-2001 14589
aerosol 8-2000 14590
aerosol 2-2001 14591
aerosol 2-2001 14592
aerosol 1-2001 14593
aerosol 1-2001 14594
aerosol 2-2001 14595
aerosol 2-2001 14596
aerosol 1-2001 14597
aerosol 1-2001 14598
aerosol 1-2001 14599
aerosol 2-2001 14600
aerosol 1-2001 14601
aerosol 1-2001 14602
aerosol 1-2001 14603
aerosol 1-2001 14604
aerosol 2-2001 14605
aerosol 1-2001 14606
aerosol 1-2001 14607
aerosol 1-2009 14608
aerosol 1-2009 14609
aerosol 1-2003 14611
aerosol 5-2000 14612
aerosol 2-2001 14613
aerosol 5-2001 14614
aerosol 12-2000 14615
aerosol 12-2000 14619

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year,rain,temp,soil_temp,optical_thickness,transmission_percent
0,2862662347,"Canis latrans Say, 1823",34.699630,-119.241698,9,9,2020,NaN,NaN,NaN,NaN,NaN
1,2862658329,"Canis latrans Say, 1823",25.965225,-97.257489,12,8,2019,170.9,29.1,27.1,0.112457,89.363620
2,2862652416,"Canis latrans Say, 1823",43.083987,-89.294833,7,9,2020,NaN,NaN,NaN,NaN,NaN
3,2862630361,"Canis latrans Say, 1823",32.710595,-99.730371,13,11,2019,4.4,12.2,9.4,0.206200,81.367033
4,2862630337,"Canis latrans Say, 1823",32.872760,-96.739678,9,9,2020,NaN,NaN,NaN,NaN,NaN
5,2862625324,"Canis latrans Say, 1823",37.949792,-121.917237,22,2,2019,157.7,9.3,-1.9,0.112656,89.345837
6,2862571831,"Canis latrans Say, 1823",49.001145,-122.575517,12,8,2018,0.0,21.5,20.0,0.442568,64.238461
7,2862569038,"Canis latrans Say, 1823",35.976713,-112.125222,6,9,2020,NaN,NaN,NaN,NaN,NaN
8,2862568781,"Canis latrans Say, 1823",41.987148,-87.688472,24,8,2020,24.3,23.9,25.0,NaN,NaN
9,2862568608,"Canis latrans Say, 1823",33.142740,-116.849391,31,8,2020,0.0,22.1,21.0,NaN,NaN
10,2862561916,"Canis latrans Say, 1823",30.586545,-97.692273,6,9,2020,NaN,NaN,NaN,NaN,NaN
11,2862559617,"Canis latrans Say, 1823",33.189066,-116.319656,2,9,2020,NaN,NaN,NaN,NaN,NaN
12,2862554747,"Canis latrans Say, 1823",33.189152,-116.320085,5,9,2020,NaN,NaN,NaN,NaN,NaN
13,2862554670,"Canis latrans Say, 1823",34.178231,-118.506592,9,6,2019,1.8,20.8,16.6,0.070020,93.237540
14,2862554618,"Canis latrans Say, 1823",33.188923,-116.319913,4,9,2020,NaN,NaN,NaN,NaN,NaN

In [35]:
main_df.isnull().sum()

gbifID                     0
scientificName             0
decimalLatitude            0
decimalLongitude           0
day                        0
month                      0
year                       0
rain                     624
temp                      62
soil_temp               1124
optical_thickness       1620
transmission_percent    1620
dtype: int64

In [36]:
main_df.tail()

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year,rain,temp,soil_temp,optical_thickness,transmission_percent
14616,476839066,"Canis latrans Say, 1823",41.617264,-70.475302,27,11,2001,19.4,9.3,5.5,0.5507,57.654609
14617,476836969,"Canis latrans Say, 1823",41.700111,-70.032794,23,5,2002,107.8,13.3,12.2,0.0926,91.155805
14618,476813864,"Canis latrans Say, 1823",41.519671,-71.372254,1,1,2005,30.1,-9.9,-0.2,0.0619,93.997688
14619,476809540,"Canis latrans Say, 1823",41.700110,-70.299466,8,12,2000,94.6,-0.6,2.2,NaN,NaN
14620,202062058,"Canis latrans Say, 1823",35.230056,-97.297253,2,4,2005,82.0,14.4,17.7,0.1497,86.096623

In [41]:
main_df.to_csv('lomdi.csv')

In [39]:
main_df = main_df.dropna()

In [8]:
df.shape

(11287, 13)

In [6]:
df = pd.read_csv('lomdi.csv')

In [7]:
df.head()

,gbifID,scientificName,decimalLatitude,decimalLongitude,day,month,year,rain,temp,soil_temp,optical_thickness,transmission_percent
0,2862658329,"Canis latrans Say, 1823",25.965225,-97.257489,12,8,2019,170.9,29.1,27.1,0.112457,89.363620
1,2862630361,"Canis latrans Say, 1823",32.710595,-99.730371,13,11,2019,4.4,12.2,9.4,0.206200,81.367033
2,2862625324,"Canis latrans Say, 1823",37.949792,-121.917237,22,2,2019,157.7,9.3,-1.9,0.112656,89.345837
3,2862571831,"Canis latrans Say, 1823",49.001145,-122.575517,12,8,2018,0.0,21.5,20.0,0.442568,64.238461
4,2862554670,"Canis latrans Say, 1823",34.178231,-118.506592,9,6,2019,1.8,20.8,16.6,0.070020,93.237540

In [1]:
!pip install gmplot

Collecting gmplot
  Downloading gmplot-1.4.1-py3-none-any.whl (164 kB)
Requirement already satisfied: requests in c:\users\cmgupta159\anaconda3\lib\site-packages (from gmplot) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\cmgupta159\anaconda3\lib\site-packages (from requests->gmplot) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\cmgupta159\anaconda3\lib\site-packages (from requests->gmplot) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cmgupta159\anaconda3\lib\site-packages (from requests->gmplot) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\cmgupta159\anaconda3\lib\site-packages (from requests->gmplot) (1.25.9)
Installing collected packages: gmplot
Successfully installed gmplot-1.4.1

In [10]:
import gmplot 
import numpy as np
latitude_list = np.array(df['decimalLatitude'])
  
longitude_list = np.array(df['decimalLongitude'])
gmap4 = gmplot.GoogleMapPlotter(30.3164945, 
                                78.03219179999999, 13) 
  
# heatmap plot heating Type 
# points on the Google map 
gmap4.heatmap( latitude_list, longitude_list ) 
  
gmap4.draw( "C:\\Users\\cmgupta159\\Desktop\\map14.html")

In [3]:
df = pd.read_csv('LST_Day_CMG.csv')

,NaN,NaN.1,NaN.2,NaN.3,NaN.4,NaN.5,NaN.6,NaN.7,NaN.8,NaN.9,...,NaN.7190,NaN.7191,NaN.7192,NaN.7193,NaN.7194,NaN.7195,NaN.7196,NaN.7197,NaN.7198,NaN.7199
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3594,NaN,NaN,NaN,NaN,205.12,205.12,205.12,205.12,205.12,205.12,...,204.80,204.80,204.80,204.80,204.80,204.8,NaN,NaN,NaN,NaN
3595,NaN,NaN,NaN,NaN,NaN,204.14,204.14,204.14,204.14,204.14,...,205.06,205.06,205.06,205.06,205.06,NaN,NaN,NaN,NaN,NaN
3596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205.10,...,205.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN